const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Define collection and schema
let FormOpi = new Schema({
    BasicDetails: [{
        OPI_Sec_A_Name: { type: String },
        OPI_Sec_A_LEI: { type: String },
        OPI_Sec_A_PAN: { type: String },
        OPI_Sec_A_Address: { type: String },
        OPI_Sec_A_City: { type: String },
        OPI_Sec_A_State: { type: String },
        OPI_Sec_A_PIN: { type: String },
        OPI_Sec_A_NetINR: { type: Number },
        WhetherIElist: { type: String },
        OPI_Sec_A_ForeignName: { type: String },
        OPI_Sec_A_SharesRepurchased: { type: Number },
        OPI_Sec_A_SharesIssued: { type: Number },
        OPI_Sec_A_ContactPersonName: { type: String },
        OPI_Sec_A_ContactPersonDesignation: { type: String },
        OPI_Sec_A_ContactPerson: { type: String },
        OPI_Sec_A_Mobile: { type: String },
        OPI_Sec_A_EmailId: { type: String }
    }],
    IndianEntitysDetails: [{
        OPI_Sec_A_NetAmount_USD: { type: Number },
        OPI_Sec_A_NetAmount_INR: { type: Number },
        OPI_Sec_A_Investments_USD: { type: Number },
        OPI_Sec_A_Investments_INR: { type: Number },
        OPI_Sec_A_Sale_USD: { type: Number },
        OPI_Sec_A_Sale_INR: { type: Number },
        OPI_Sec_A_NetAmountClosing_USD: { type: Number },
        OPI_Sec_A_NetAmountClosing_INR: { type: Number },
        OPI_Sec_A_RemittanceAmt_USD: { type: Number },
        OPI_Sec_A_RemittanceAmt_INR: { type: Number },
        OPI_Sec_A_Repatriation_USD: { type: Number },
        OPI_Sec_A_Repatriation_INR: { type: Number }
    }],
    ResidentIndividualDetails: [{
        OPI_Sec_A_EBS_NetAmt_USD: { type: Number },
        OPI_Sec_A_EBS_NetAmt_INR: { type: Number },
        OPI_Sec_A_EBS_Investments_USD: { type: Number },
        OPI_Sec_A_EBS_Investments_INR: { type: Number },
        OPI_Sec_A_EBS_Disinvestment_USD: { type: Number },
        OPI_Sec_A_EBS_Disinvestment_INR: { type: Number },
        OPI_Sec_A_EBS_NetAmtClose_USD: { type: Number },
        OPI_Sec_A_EBS_NetAmtClose_INR: { type: Number },
        OPI_Sec_A_EBS_RemittanceAmt_USD: { type: Number },
        OPI_Sec_A_EBS_RemittanceAmt_INR: { type: Number },
        OPI_Sec_A_EBS_RepatriationAmt_USD: { type: Number },
        OPI_Sec_A_EBS_RepatriationAmt_INR: { type: Number }
    }],
    MutualFundDetails: [{
        OPI_Sec_A_Equity1_USD: { type: Number },
        OPI_Sec_A_Equity2_INR: { type: Number },
        OPI_Sec_A_Equity3_USD: { type: Number },
        OPI_Sec_A_Equity4_INR: { type: Number },
        OPI_Sec_A_Equity5_USD: { type: Number },
        OPI_Sec_A_Equity6_INR: { type: Number },
        OPI_Sec_A_Equity7_USD: { type: Number },
        OPI_Sec_A_Equity8_INR: { type: Number },
        OPI_Sec_A_Equity9_USD: { type: Number },
        OPI_Sec_A_Equity10_INR: { type: Number },
        OPI_Sec_A_Equity11_USD: { type: Number },
        OPI_Sec_A_Equity12_INR: { type: Number },
        OPI_Sec_A_DebtInstrument1_USD: { type: Number },
        OPI_Sec_A_DebtInstrument2_INR: { type: Number },
        OPI_Sec_A_DebtInstrument3_USD: { type: Number },
        OPI_Sec_A_DebtInstrument4_INR: { type: Number },
        OPI_Sec_A_DebtInstrument5_USD: { type: Number },
        OPI_Sec_A_DebtInstrument6_INR: { type: Number },
        OPI_Sec_A_DebtInstrument7_USD: { type: Number },
        OPI_Sec_A_DebtInstrument8_INR: { type: Number },
        OPI_Sec_A_DebtInstrument9_USD: { type: Number },
        OPI_Sec_A_DebtInstrument10_INR: { type: Number },
        OPI_Sec_A_DebtInstrument11_USD: { type: Number },
        OPI_Sec_A_DebtInstrument12_INR: { type: Number },
        OPI_Sec_A_ADR_GDR1_USD: { type: Number },
        OPI_Sec_A_ADR_GDR2_INR: { type: Number },
        OPI_Sec_A_ADR_GDR3_USD: { type: Number },
        OPI_Sec_A_ADR_GDR4_INR: { type: Number },
        OPI_Sec_A_ADR_GDR5_USD: { type: Number },
        OPI_Sec_A_ADR_GDR6_INR: { type: Number },
        OPI_Sec_A_ADR_GDR7_USD: { type: Number },
        OPI_Sec_A_ADR_GDR8_INR: { type: Number },
        OPI_Sec_A_ADR_GDR9_USD: { type: Number },
        OPI_Sec_A_ADR_GDR10_INR: { type: Number },
        OPI_Sec_A_ADR_GDR11_USD: { type: Number },
        OPI_Sec_A_ADR_GDR12_INR: { type: Number },
        OPI_Sec_A_ETF1_USD: { type: Number },
        OPI_Sec_A_ETF2_INR: { type: Number },
        OPI_Sec_A_ETF3_USD: { type: Number },
        OPI_Sec_A_ETF4_INR: { type: Number },
        OPI_Sec_A_ETF5_USD: { type: Number },
        OPI_Sec_A_ETF6_INR: { type: Number },
        OPI_Sec_A_ETF7_USD: { type: Number },
        OPI_Sec_A_ETF8_INR: { type: Number },
        OPI_Sec_A_ETF9_USD: { type: Number },
        OPI_Sec_A_ETF10_INR: { type: Number },
        OPI_Sec_A_ETF11_USD: { type: Number },
        OPI_Sec_A_ETF12_INR: { type: Number },
        OPI_Sec_A_Mutual1_USD: { type: Number },
        OPI_Sec_A_Mutual2_INR: { type: Number },
        OPI_Sec_A_Mutual3_USD: { type: Number },
        OPI_Sec_A_Mutual4_INR: { type: Number },
        OPI_Sec_A_Mutual5_USD: { type: Number },
        OPI_Sec_A_Mutual6_INR: { type: Number },
        OPI_Sec_A_Mutual7_USD: { type: Number },
        OPI_Sec_A_Mutual8_INR: { type: Number },
        OPI_Sec_A_Mutual9_USD: { type: Number },
        OPI_Sec_A_Mutual10_INR: { type: Number },
        OPI_Sec_A_Mutual11_USD: { type: Number },
        OPI_Sec_A_Mutual12_INR: { type: Number },
        OPI_Sec_A_Others1_USD: { type: Number },
        OPI_Sec_A_Others2_INR: { type: Number },
        OPI_Sec_A_Others3_USD: { type: Number },
        OPI_Sec_A_Others4_INR: { type: Number },
        OPI_Sec_A_Others5_USD: { type: Number },
        OPI_Sec_A_Others6_INR: { type: Number },
        OPI_Sec_A_Others7_USD: { type: Number },
        OPI_Sec_A_Others8_INR: { type: Number },
        OPI_Sec_A_Others9_USD: { type: Number },
        OPI_Sec_A_Others10_INR: { type: Number },
        OPI_Sec_A_Others11_USD: { type: Number },
        OPI_Sec_A_Others12_INR: { type: Number },
        OPI_Sec_A_Total1_USD: { type: Number },
        OPI_Sec_A_Total2_INR: { type: Number },
        OPI_Sec_A_Total3_USD: { type: Number },
        OPI_Sec_A_Total4_INR: { type: Number },
        OPI_Sec_A_Total5_USD: { type: Number },
        OPI_Sec_A_Total6_INR: { type: Number },
        OPI_Sec_A_Total7_USD: { type: Number },
        OPI_Sec_A_Total8_INR: { type: Number },
        OPI_Sec_A_Total9_USD: { type: Number },
        OPI_Sec_A_Total10_INR: { type: Number },
        OPI_Sec_A_Total11_USD: { type: Number },
        OPI_Sec_A_Total12_INR: { type: Number }
    }],
    VCFAIFDetails: [{
        OPI_Sec_B_Name: { type: String },
        OPI_Sec_B_LEI: { type: String },
        OPI_Sec_B_PAN: { type: String },
        OPI_Sec_B_Group: { type: String },
        OPI_Sec_B_Activity: { type: String },
        OPI_Sec_B_Address: { type: String },
        OPI_Sec_B_City: { type: String },
        OPI_Sec_B_State: { type: String },
        OPI_Sec_B_PINCode: { type: String },
        OPI_Sec_B_ContactPerson: { type: String },
        OPI_Sec_B_Designation: { type: String },
        OPI_Sec_B_Telephone: { type: String },
        OPI_Sec_B_MobileCP: { type: String },
        OPI_Sec_B_FaxNo: { type: String },
        OPI_Sec_B_Email: { type: String },
        OPI_Sec_B_VCF_Name: { type: String },
        OPI_Sec_B_VCF_PAN: { type: String },
        OPI_Sec_B_VCF_Group: { type: String },
        OPI_Sec_B_VCF_Activity: { type: String },
        OPI_Sec_B_VCF_Address: { type: String },
        OPI_Sec_B_VCF_City: { type: String },
        OPI_Sec_B_VCF_State: { type: String },
        OPI_Sec_B_VCF_PINCode: { type: String },
        OPI_Sec_B_VCF_ContactPerson: { type: String },
        OPI_Sec_B_VCF_Designation: { type: String },
        OPI_Sec_B_VCF_Telephone: { type: String },
        OPI_Sec_B_VCF_Email: { type: String },
        OPI_Sec_B_AIF_Name: { type: String },
        OPI_Sec_B_AIF_Date: { type: Date },
        OPI_Sec_B_AIF_SEBILimit: { type: Number },
    
        OPI_Sec_B_Equity1_USD: { type: Number },
        OPI_Sec_B_Equity2_INR: { type: Number },
        OPI_Sec_B_Equity3_USD: { type: Number },
        OPI_Sec_B_Equity4_INR: { type: Number },
        OPI_Sec_B_Equity5_USD: { type: Number },
        OPI_Sec_B_Equity6_INR: { type: Number },
        OPI_Sec_B_Equity7_USD: { type: Number },
        OPI_Sec_B_Equity8_INR: { type: Number },
        OPI_Sec_B_Equity9_USD: { type: Number },
        OPI_Sec_B_Equity10_INR: { type: Number },
        OPI_Sec_B_Equity11_USD: { type: Number },
        OPI_Sec_B_Equity12_INR: { type: Number },
    
        OPI_Sec_B_EquityLinked1_USD: { type: Number },
        OPI_Sec_B_EquityLinked2_INR: { type: Number },
        OPI_Sec_B_EquityLinked3_USD: { type: Number },
        OPI_Sec_B_EquityLinked4_INR: { type: Number },
        OPI_Sec_B_EquityLinked5_USD: { type: Number },
        OPI_Sec_B_EquityLinked6_INR: { type: Number },
        OPI_Sec_B_EquityLinked7_USD: { type: Number },
        OPI_Sec_B_EquityLinked8_INR: { type: Number },
        OPI_Sec_B_EquityLinked9_USD: { type: Number },
        OPI_Sec_B_EquityLinked10_INR: { type: Number },
        OPI_Sec_B_EquityLinked11_USD: { type: Number },
        OPI_Sec_B_EquityLinked12_INR: { type: Number },
    
        OPI_Sec_B_Permissible1_USD: { type: Number },
        OPI_Sec_B_Permissible2_INR: { type: Number },
        OPI_Sec_B_Permissible3_USD: { type: Number },
        OPI_Sec_B_Permissible4_INR: { type: Number },
        OPI_Sec_B_Permissible5_USD: { type: Number },
        OPI_Sec_B_Permissible6_INR: { type: Number },
        OPI_Sec_B_Permissible7_USD: { type: Number },
        OPI_Sec_B_Permissible8_INR: { type: Number },
        OPI_Sec_B_Permissible9_USD: { type: Number },
        OPI_Sec_B_Permissible10_INR: { type: Number },
        OPI_Sec_B_Permissible11_USD: { type: Number },
        OPI_Sec_B_Permissible12_INR: { type: Number },
    
        OPI_Sec_B_Total1_USD: { type: Number },
        OPI_Sec_B_Total2_INR: { type: Number },
        OPI_Sec_B_Total3_USD: { type: Number },
        OPI_Sec_B_Total4_INR: { type: Number },
        OPI_Sec_B_Total5_USD: { type: Number },
        OPI_Sec_B_Total6_INR: { type: Number },
        OPI_Sec_B_Total7_USD: { type: Number },
        OPI_Sec_B_Total8_INR: { type: Number },
        OPI_Sec_B_Total9_USD: { type: Number },
        OPI_Sec_B_Total10_INR: { type: Number },
        OPI_Sec_B_Total11_USD: { type: Number },
        OPI_Sec_B_Total12_INR: { type: Number }
    }],
    SectionCDetails:[{
        OPI_Sec_C_Signature: { type: String },
        OPI_Sec_C_Name: { type: String },
        OPI_Sec_C_Stamp: { type: String },
        OPI_Sec_C_Place: { type: String },
        OPI_Sec_C_Date: { type: Date },
        OPI_Sec_C_Telephone: { type: String },
        OPI_Sec_C_EmailId: { type: String }
    }]
}, {
    collection: 'formopi'
})
module.exports = mongoose.model('FormOpi', FormOpi)